name: Build and Publish to NPM Registry

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build JS package
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dist-artifact
          path: ./dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-metadata-artifact
          path: |
            package.json
            README.md
            License.md

  publish-package:
    needs: build-package
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dist-artifact
          path: ./dist

      - name: Download metadata artifact
        uses: actions/download-artifact@v4
        with:
          name: release-metadata-artifact
          path: .

      - name: Install and Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Update npm to latest
        run: npm install -g npm@latest

      - name: Publish to npm via OIDC
        run: npm publish --ignore-scripts
